on: 
   push:
      branches: [main]

jobs:
   test:
     uses: ./.github/workflows/Development.yml
   
   build:
     name: Build Application
     runs-on: ubuntu-latest
     needs: test
     steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        # setup node
        - name: Setup node
          uses: actions/setup-node@v3
          with:
              node-version: '18.x'
       # install dependencies
        - name: Install dependencies
          run: npm ci
       # build the project
        - name: Build the Project
          run: npm run "Production build"
       # upload build artifact -> use actions/upload-pages-artifact@v2
        - uses: actions/upload-pages-artifact@v2
        with:
        name: Build
        path: dist

   deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: setup github pages
        uses: actions/configure-pages@v3
      - name: download the build artifacts
        uses: actions/download-artifact@v3
      - name: deploy to github pages
        uses: actions/deploy-pages@v2
        
   #deployment:
     # should run AFTER test and build (see `needs`) 
     #steps:
       # checkout the repo
       # setup github pages -> use actions/configure-pages@v3
       # download the build artifacts -> use actions/download-artifact@v3
       # deploy to github pages -> use actions/deploy-pages@v2  
